CHAINS = {
    "bitcoin": {
        "name": "Bitcoin",
        "symbol": "BTC",
        "chain_id": "bitcoin",
        "explorer_api": "https://blockstream.info/api",
        "explorer_url": "https://blockstream.info",
        "rpc": "https://blockstream.info/api",
        "native_price_id": "bitcoin",
        "gas_api": "blockstream",
    },
    "ethereum": {
        "name": "Ethereum",
        "symbol": "ETH",
        "chain_id": 1,
        "explorer_api": "https://api.etherscan.io/v2/api",
        "explorer_url": "https://etherscan.io",
        "rpc": "https://eth.llamarpc.com",
        "native_price_id": "ethereum",
        "gas_api": "etherscan",
    },
    "solana": {
        "name": "Solana",
        "symbol": "SOL",
        "chain_id": "solana",
        "explorer_api": "https://public-api.solscan.io",
        "explorer_url": "https://solscan.io",
        "rpc": "https://api.mainnet-beta.solana.com",
        "native_price_id": "solana",
        "gas_api": "solana",
    },
    "bsc": {
        "name": "BNB Chain",
        "symbol": "BNB",
        "chain_id": 56,
        "goldrush_chain_id": "bsc-mainnet",
        "explorer_api": "https://api.etherscan.io/v2/api",
        "explorer_url": "https://bscscan.com",
        "rpc": "https://bsc-dataseed1.binance.org",
        "native_price_id": "binancecoin",
        "gas_api": "etherscan",
    },
    "polygon": {
        "name": "Polygon",
        "symbol": "MATIC",
        "chain_id": 137,
        "explorer_api": "https://api.etherscan.io/v2/api",
        "explorer_url": "https://polygonscan.com",
        "rpc": "https://polygon-bor-rpc.publicnode.com",
        "native_price_id": "matic-network",
        "gas_api": "etherscan",
    },
    "arbitrum": {
        "name": "Arbitrum",
        "symbol": "ETH",
        "chain_id": 42161,
        "goldrush_chain_id": "arbitrum-mainnet",
        "explorer_api": "https://api.etherscan.io/v2/api",
        "explorer_url": "https://arbiscan.io",
        "rpc": "https://arb1.arbitrum.io/rpc",
        "native_price_id": "ethereum",
        "gas_api": "etherscan",
    },
    "base": {
        "name": "Base",
        "symbol": "ETH",
        "chain_id": 8453,
        "explorer_api": "https://api.etherscan.io/v2/api",
        "explorer_url": "https://basescan.org",
        "rpc": "https://mainnet.base.org",
        "native_price_id": "ethereum",
        "gas_api": "etherscan",
    },
    "optimism": {
        "name": "Optimism",
        "symbol": "ETH",
        "chain_id": 10,
        "explorer_api": "https://api.etherscan.io/v2/api",
        "explorer_url": "https://optimistic.etherscan.io",
        "rpc": "https://mainnet.optimism.io",
        "native_price_id": "ethereum",
        "gas_api": "etherscan",
    },
    "avalanche": {
        "name": "Avalanche",
        "symbol": "AVAX",
        "chain_id": 43114,
        "explorer_api": "https://api.etherscan.io/v2/api",
        "explorer_url": "https://snowtrace.io",
        "rpc": "https://api.avax.network/ext/bc/C/rpc",
        "native_price_id": "avalanche-2",
        "gas_api": "etherscan",
    },
}


WHALE_ADDRESSES = {
    "ethereum": [
        {"address": "0x00000000219ab540356cBB839Cbe05303d7705Fa", "label": "ETH 2.0 Deposit Contract"},
        {"address": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2", "label": "Wrapped ETH (WETH)"},
        {"address": "0x4838B106FCe9647Bdf1E7877BF73cE8B0BAD5f97", "label": "Vitalik Buterin"},
        {"address": "0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18", "label": "Bitfinex Hot Wallet"},
        {"address": "0xDFd5293D8e347dFe59E90eFd55b2956a1343963d", "label": "OKX Hot Wallet"},
    ],
    "bsc": [
        {"address": "0xF977814e90dA44bFA03b6295A0616a897441aceC", "label": "Binance Hot Wallet"},
        {"address": "0xBE0eB53F46cd790Cd13851d5EFf43D12404d33E8", "label": "Binance Cold Wallet"},
        {"address": "0x8894E0a0c962CB723c1ef8a1B6764b68f7a0e5d1", "label": "Binance Hot Wallet 2"},
        {"address": "0x1CB6b80bB8dA4c6B5253E64751E18E0a3895c43a", "label": "PancakeSwap Router"},
        {"address": "0x5Db4796189cA745d7ff0EdF3A96bD8980c79d4E9", "label": "Venus Protocol"},
        {"address": "0x0000000000000000000000000000000000001004", "label": "BSC Native Staking"},
    ],
    "polygon": [
        {"address": "0x0000000000000000000000000000000000001010", "label": "MATIC Staking"},
        {"address": "0x3E93Fbb004C722750606A8086a2Dbde12708D206", "label": "Aave Polygon Pool"},
        {"address": "0xD9e1cE17f2641f24aE83637ab66a2cca9C378B9F", "label": "SushiSwap Router"},
    ],
    "arbitrum": [
        {"address": "0xC35DADB65012eC5796536bD9864eD8773aBc74C4", "label": "Uniswap Router"},
        {"address": "0x1F98431c8aD98523631AE4a59f267346ea31F984", "label": "Uniswap Factory"},
    ],
    "base": [
        {"address": "0x2626664c2603336E57B271c5C0b26F421741e481", "label": "Uniswap Router"},
    ],
    "optimism": [
        {"address": "0x2502B2bB8F287082b6E323E73C30D1D3F58de575", "label": "Synthetix Staking"},
        {"address": "0xE592427A0AEce92De3Edee1F18E0157C05861564", "label": "Uniswap Router"},
    ],
    "avalanche": [
        {"address": "0x8b83e91e28F8A7D8B5a4b6B22c2F9B7B83C9C2F1", "label": "Bent Finance"},
        {"address": "0x60aE6168C76500e9E4c16037675Bc5d4e1B10552", "label": "Trader Joe Router"},
    ],
    "solana": [
        {"address": "5tzFkiKscjHKsN2FzXoyFBfiDjQJt3GFZx8p3bHkxQBY", "label": "Binance Solana"},
        {"address": "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM", "label": "Coinbase Solana"},
    ],
}


CHAIN_TOKEN_MAP = {
    "ethereum": {"usdt": "tether", "usdc": "usd-coin", "dai": "dai", "link": "chainlink", "uniswap": "uniswap", "aave": "aave", "lido": "lido-dao"},
    "bsc": {"usdt": "tether", "usdc": "usd-coin", "cake": "pancakeswap-token", "xvs": "venus", "btcb": "bitcoin-bep2"},
    "polygon": {"usdt": "tether", "usdc": "usd-coin", "quick": "quickswap", "aave": "aave"},
    "arbitrum": {"usdt": "tether", "usdc": "usd-coin", "gmx": "gmx", "pendle": "pendle"},
    "base": {"usdt": "tether", "usdc": "usd-coin", "aerodrome": "aerodrome-finance", "brett": "brett"},
    "optimism": {"usdt": "tether", "usdc": "usd-coin", "op": "optimism", "velo": "velodrome-finance"},
    "avalanche": {"usdt": "tether", "usdc": "usd-coin", "joe": "joe", "png": "pangolin"},
    "solana": {"usdt": "tether", "usdc": "usd-coin", "raydium": "raydium", "jup": "jupiter-exchange-solana", "bonk": "bonk"},
}
